export const copy = {
  zh: {
    appName: "海外广告联盟业务提效 POC：嵌入式 AI 辅助诊断",
    appShort: "Embedded AI Assistant",
    subtitle: "AI 嵌入广告主、开发者与内部运营的既有业务流程",
    mockDate: "模拟数据日期：2026-05-21",
    role: "角色",
    language: "语言",
    roles: {
      advertiser: "广告主",
      developer: "开发者",
      operator: "内部运营"
    },
    generation: {
      loading: "正在生成 AI 辅助解释...",
      success: "AI 辅助解释已更新",
      fallback: "生成暂不可用，已展示模拟辅助结果"
    },
    nav: {
      overview: "流程概览",
      advertiser: "广告主投放",
      developer: "开发者收益",
      copilot: "运营工作台",
      followup: "闭环追踪"
    },
    overview: {
      title: "AI 辅助诊断摘要",
      desc: "本 POC 模拟 AI 能力如何嵌入海外广告联盟的关键业务流程，而不是单独搭建 AI 平台。业务数据先发现问题，规则先识别与拆解异常，AI 再辅助解释、写作和沟通。",
      anomalies: "规则识别异常",
      reports: "AI 辅助次数",
      review: "待人工确认",
      monitoring: "观察中指标",
      flowTitle: "嵌入式辅助链路",
      flow: ["查看业务数据", "规则识别", "AI 辅助解释", "人工确认", "指标回看"],
      roleTitle: "三个高频业务流程",
      reviewQueue: "待人工确认 (5)",
      viewAll: "查看全部",
      chartTitle: "AI 辅助价值概览",
      chartLabel: "趋势图表（模拟）",
      collaborationTitle: "人机协作原则",
      advertiserTitle: "广告主投放看板 + AI 异常解释",
      developerTitle: "开发者收益看板 + AI 收益波动分析",
      operatorTitle: "内部运营工作台 + AI 报告辅助",
      advertiserDesc: "在 CPA、ROAS 或预算利用率异常后，生成证据绑定的解释与客户话术。",
      developerDesc: "在收入、填充率或 eCPM 波动后，拆解广告源与广告位影响。",
      operatorDesc: "基于已有诊断结果生成周报、邮件和跟进记录，降低重复整理成本。",
      principlesTitle: "设计原则",
      principles: ["业务问题优先", "规则先行，AI 解释", "高风险动作人工确认", "用指标验证价值"]
    },
    filters: {
      account: "广告账户",
      campaign: "广告计划",
      app: "App",
      placement: "广告位",
      country: "国家 / 地区",
      source: "广告源",
      range: "时间范围",
      issue: "问题类型",
      task: "任务模板",
      context: "关联上下文",
      output: "输出语言",
      extra: "补充要求"
    },
    advertiser: {
      title: "广告主投放看板 + AI 异常解释",
      desc: "业务场景：广告主或运营人员在既有投放看板发现美国市场近 7 日 CPA 上升、ROAS 下降，再调用嵌入式 AI 解释异常并准备沟通动作。",
      account: "Galaxy Quest Studio",
      campaign: "US RPG User Acquisition",
      range: "近 7 日 vs 前 7 日",
      issue: "CPA 上升 / ROAS 下降",
      trends: "业务指标趋势",
      breakdown: "证据维度拆解",
      country: "国家表现",
      creative: "素材表现",
      report: "AI 辅助异常解释",
      run: "生成 AI 解释",
      rule: "近 7 日 CPA 较历史均值上升 28%，超过 20% 预警阈值；ROAS 同期下降 18%。",
      decomposition: "CTR 基本稳定，而 CVR 从 5.1% 降至 3.4%；美国地区广告组与核心素材贡献最大影响。",
      summary: "近 7 日 CPA 上升 28%，ROAS 下降 18%。CTR 基本稳定，但 CVR 从 5.1% 降至 3.4%，主要影响来自美国市场的 Boss Battle Reward Video 素材。",
      cause1: "CVR 显著下降，问题更可能发生在落地页、转化回传或用户匹配环节。",
      cause2: "核心素材进入疲劳期，点击质量下降，但 CTR 尚未明显下滑。",
      rec1: "优先检查美国落地页加载速度与转化回传链路。",
      rec2: "测试与素材卖点一致性更强的落地页版本。",
      rec3: "为 Boss Battle Reward Video 准备 2 个新素材变体，观察 48 小时 CVR。",
      risk: "在确认转化回传前，不建议直接提高预算，避免放大无效消耗。"
    },
    developer: {
      title: "开发者收益看板 + AI 收益波动分析",
      desc: "业务场景：开发者或开发者运营在收益看板发现巴西激励视频收入下降，在不直接改配置的前提下调用 AI 辅助拆解原因。",
      app: "Puzzle Island",
      placement: "Rewarded Video - Level Complete",
      country: "Brazil",
      source: "All Sources",
      range: "昨日 vs 前日",
      trends: "业务收益趋势",
      breakdown: "维度拆解",
      sources: "广告源表现",
      report: "AI 辅助收益波动分析",
      run: "生成 AI 分析",
      rule: "昨日广告收入下降 18%，超过 15% 预警阈值；巴西地区激励视频填充率异常下降。",
      decomposition: "请求量基本稳定，但填充率从 82% 降至 61%；广告源 B 的覆盖下降是主要贡献因素。",
      summary: "昨日广告收入下降 18%，主要来自巴西地区激励视频广告位。请求量基本稳定，但填充率从 82% 降至 61%，广告源 B 填充下降明显。",
      cause1: "请求量稳定说明流量侧未明显萎缩，收入下降主要由填充率下降驱动。",
      cause2: "广告源 B 在巴西的返回率异常，可能与预算覆盖或国家定向有关。",
      rec1: "检查广告源 B 的预算覆盖、国家定向和返回错误。",
      rec2: "临时提升备用广告源 C 的优先级，降低填充缺口。",
      rec3: "观察未来 24 小时 Fill Rate、Revenue 和 eCPM 是否恢复。",
      risk: "调整瀑布流优先级可能影响 eCPM，需要同步观察收入和单价。"
    },
    copilot: {
      title: "内部运营工作台 + AI 报告辅助",
      desc: "业务场景：运营、销售或客户成功人员先查看客户异常和最近诊断，再使用嵌入式 AI 辅助生成周报、邮件与后续跟进内容。",
      weekly: "生成客户周报",
      review: "生成异常复盘",
      message: "生成对外沟通话术",
      ticket: "总结工单并给出处理建议",
      placeholder: "例如：语气更适合对客户 CEO 汇报，压缩为 3 个要点。",
      generate: "生成内容",
      profile: "客户画像",
      metrics: "核心变化",
      reasons: "异常原因",
      external: "对外沟通话术",
      internal: "内部备注",
      risk: "风险提醒",
      queue: "客户 / 开发者重点事项",
      recent: "最近诊断结果",
      draft: "AI 报告初稿",
      rule: "本周客户 A 消耗下降 12%，关联诊断显示美国广告组 A 的 CVR 下滑为主要异常。",
      decomposition: "复用广告主看板中已验证的指标拆解与证据，不由 AI 自行推测原始原因。",
      profileText: "Galaxy Quest Studio 是海外手游广告主，当前重点投放美国 RPG 买量计划，目标为提升付费转化和 7 日 ROAS。",
      metricText: "本周 CPA 上升 28%，ROAS 下降 18%，主要由 CVR 从 5.1% 下滑至 3.4% 导致。",
      reasonText: "CTR 基本稳定，说明点击吸引力未显著恶化；CVR 下滑更可能与落地页、转化回传或用户匹配有关。",
      externalText: "我们已定位到本周成本上升主要来自美国市场转化率波动，建议先检查落地页加载和转化回传链路，同时准备新的素材与落地页组合测试。",
      internalText: "建议客户成功团队先确认 MMP 回传延迟和落地页变更记录，再讨论预算调整。",
      riskText: "不要在转化链路未确认前承诺预算放量效果。"
    },
    followup: {
      title: "建议闭环追踪",
      desc: "跟进优化建议的处理状态，查看关键指标在 24 小时或 7 天内的变化。",
      status: "状态",
      source: "来源",
      priority: "优先级",
      owner: "负责人",
      window: "观察窗口",
      before: "采纳前",
      after: "当前",
      result: "结果",
      improved: "改善",
      monitoring: "观察中",
      accepted: "已采纳",
      rejected: "暂不采纳",
      review: "需要复核",
      markAccepted: "标记采纳",
      markReview: "标记复核",
      markRejected: "暂不采纳"
    },
    report: {
      evidence: "证据数据",
      causes: "AI 辅助解释",
      recommendations: "建议动作",
      risk: "风险提示",
      watch: "后续观察指标",
      confidence: "置信度",
      high: "高",
      medium: "中",
      manual: "需要复核",
      ruleTitle: "规则识别结果",
      decomposition: "指标拆解",
      boundary: "人工确认边界",
      boundaryText: "预算调整、出价修改、广告源切换和关键配置变更仅提供建议，不自动执行。",
      fitTitle: "为什么这里适合 AI 辅助？",
      fitItems: ["涉及多指标和多维度拆解，人工排查与表达成本高。", "普通报表能展示变化，但难以直接生成可沟通的原因说明。", "AI 输出绑定证据数据，并由业务人员确认后再推进。"],
      valueTitle: "AI 辅助价值衡量",
      simulated: "模拟数据",
      actions: "业务动作"
    }
  },
  en: {
    appName: "Overseas Ad Network Embedded AI Assistant POC",
    appShort: "Embedded AI Assistant",
    subtitle: "AI assistance embedded in advertiser, developer, and operations workflows",
    mockDate: "Mock data date: 2026-05-21",
    role: "Role",
    language: "Language",
    roles: {
      advertiser: "Advertiser",
      developer: "Developer",
      operator: "Operator"
    },
    generation: {
      loading: "Generating AI-assisted explanation...",
      success: "AI-assisted explanation updated",
      fallback: "Generation is unavailable. Showing the simulated assisted output."
    },
    nav: {
      overview: "Flow Overview",
      advertiser: "Advertiser",
      developer: "Developer",
      copilot: "Operations",
      followup: "Follow-up Tracker"
    },
    overview: {
      title: "AI-assisted Diagnosis Summary",
      desc: "This POC demonstrates AI capabilities embedded in key overseas ad network workflows rather than a standalone AI platform. Business data surfaces the issue, rules detect and decompose it, then AI assists with explanations and communication.",
      anomalies: "Rule-detected anomalies",
      reports: "AI-assisted runs",
      review: "Pending human reviews",
      monitoring: "Metrics monitored",
      flowTitle: "Embedded assistance flow",
      flow: ["Review metrics", "Rule detection", "AI explanation", "Human approval", "Measure outcome"],
      roleTitle: "Three high-frequency workflows",
      reviewQueue: "Pending Human Review (5)",
      viewAll: "View all",
      chartTitle: "AI Assistance Value Overview",
      chartLabel: "Trend chart (mock)",
      collaborationTitle: "Human-AI Collaboration Principles",
      advertiserTitle: "Advertiser Dashboard + AI Anomaly Explanation",
      developerTitle: "Developer Revenue Dashboard + AI Variance Analysis",
      operatorTitle: "Operations Workbench + AI Report Assistance",
      advertiserDesc: "After CPA, ROAS, or delivery anomalies surface, generate evidence-based explanations and client messaging.",
      developerDesc: "After revenue, fill rate, or eCPM changes, decompose ad source and placement impact.",
      operatorDesc: "Turn existing diagnosis results into reports, emails, and follow-ups with less repetitive work.",
      principlesTitle: "Design principles",
      principles: ["Business issue first", "Rules first, AI explains", "Human approval for risky actions", "Measure value with metrics"]
    },
    filters: {
      account: "Ad account",
      campaign: "Campaign",
      app: "App",
      placement: "Placement",
      country: "Country / Region",
      source: "Ad source",
      range: "Time range",
      issue: "Issue type",
      task: "Task template",
      context: "Linked context",
      output: "Output language",
      extra: "Extra instruction"
    },
    advertiser: {
      title: "Advertiser Dashboard + AI Anomaly Explanation",
      desc: "Workflow: an advertiser or operator detects CPA increase and ROAS decline in the existing campaign dashboard, then invokes embedded AI assistance for explanation and communication actions.",
      account: "Galaxy Quest Studio",
      campaign: "US RPG User Acquisition",
      range: "Last 7 days vs previous 7 days",
      issue: "CPA increase / ROAS decline",
      trends: "Business metric trends",
      breakdown: "Dimension breakdown",
      country: "Country performance",
      creative: "Creative performance",
      report: "AI-assisted anomaly explanation",
      run: "Generate AI explanation",
      rule: "CPA rose 28% versus the historical average over 7 days, above the 20% alert threshold; ROAS declined 18%.",
      decomposition: "CTR stayed stable while CVR fell from 5.1% to 3.4%; the US ad group and core creative drive most impact.",
      summary: "CPA increased by 28% and ROAS declined by 18% over the last 7 days. CTR stayed stable, while CVR dropped from 5.1% to 3.4%. The main impact comes from the Boss Battle Reward Video creative in the US.",
      cause1: "CVR declined significantly, so the issue is more likely in landing page performance, conversion postback, or audience match.",
      cause2: "The core creative is entering fatigue. Click quality is weakening even though CTR has not dropped sharply.",
      rec1: "Check US landing page load speed and conversion postback first.",
      rec2: "Test a landing page version that better matches the creative promise.",
      rec3: "Prepare two new variants for Boss Battle Reward Video and monitor CVR for 48 hours.",
      risk: "Do not increase budget before conversion tracking is verified, otherwise inefficient spend may be amplified."
    },
    developer: {
      title: "Developer Revenue Dashboard + AI Variance Analysis",
      desc: "Workflow: a developer or monetization operator observes rewarded-video revenue loss in Brazil, then invokes AI assistance without automatically changing configuration.",
      app: "Puzzle Island",
      placement: "Rewarded Video - Level Complete",
      country: "Brazil",
      source: "All Sources",
      range: "Yesterday vs previous day",
      trends: "Business revenue trends",
      breakdown: "Dimension breakdown",
      sources: "Ad source performance",
      report: "AI-assisted revenue variance analysis",
      run: "Generate AI analysis",
      rule: "Yesterday's ad revenue declined 18%, above the 15% alert threshold; Brazil rewarded-video fill rate is abnormal.",
      decomposition: "Requests stayed stable while fill rate fell from 82% to 61%; Ad Source B coverage loss is the main contributor.",
      summary: "Yesterday's ad revenue declined by 18%, mainly from the rewarded video placement in Brazil. Requests were stable, but fill rate dropped from 82% to 61%, with Ad Source B showing the sharpest fill decline.",
      cause1: "Stable requests indicate the traffic side is not shrinking. Revenue decline is mainly driven by fill rate loss.",
      cause2: "Ad Source B has abnormal response coverage in Brazil, possibly related to budget coverage or geo targeting.",
      rec1: "Check Ad Source B budget coverage, geo targeting, and response errors.",
      rec2: "Temporarily raise backup Ad Source C priority to reduce the fill gap.",
      rec3: "Monitor Fill Rate, Revenue, and eCPM over the next 24 hours.",
      risk: "Changing waterfall priority may affect eCPM, so revenue and price should be monitored together."
    },
    copilot: {
      title: "Operations Workbench + AI Report Assistance",
      desc: "Workflow: operations, sales, or customer-success staff review customer anomalies and recent diagnosis results first, then use embedded AI assistance for reports, emails, and follow-up records.",
      weekly: "Generate weekly report",
      review: "Generate incident review",
      message: "Generate external message",
      ticket: "Summarize ticket with action plan",
      placeholder: "Example: make it suitable for a customer CEO and compress into 3 bullets.",
      generate: "Generate content",
      profile: "Customer profile",
      metrics: "Core changes",
      reasons: "Root cause summary",
      external: "External message",
      internal: "Internal notes",
      risk: "Risk reminder",
      queue: "Priority client / developer items",
      recent: "Recent diagnosis result",
      draft: "AI report draft",
      rule: "Customer A spend declined 12% this week; linked diagnosis identifies US ad group A CVR decline as the primary anomaly.",
      decomposition: "Reuse the evidence and metric decomposition verified in the advertiser dashboard; AI does not invent raw root causes.",
      profileText: "Galaxy Quest Studio is a mobile game advertiser focused on US RPG user acquisition, paid conversion, and D7 ROAS.",
      metricText: "This week CPA increased by 28% and ROAS declined by 18%, mainly driven by CVR dropping from 5.1% to 3.4%.",
      reasonText: "CTR stayed stable, so click appeal has not clearly deteriorated. CVR loss points more toward landing page, postback, or audience match issues.",
      externalText: "We have identified that this week's cost increase is mainly related to conversion rate volatility in the US market. We recommend checking landing page loading and conversion postback first, while preparing new creative and landing page combinations for testing.",
      internalText: "Customer success should verify MMP postback delay and landing page change logs before discussing any budget adjustment.",
      riskText: "Do not promise scaling impact before the conversion path is confirmed."
    },
    followup: {
      title: "Recommendation Follow-up Tracker",
      desc: "Track recommendation status and review key metric movement over the next 24 hours or 7 days.",
      status: "Status",
      source: "Source",
      priority: "Priority",
      owner: "Owner",
      window: "Window",
      before: "Before",
      after: "Current",
      result: "Result",
      improved: "Improved",
      monitoring: "Monitoring",
      accepted: "Accepted",
      rejected: "Rejected",
      review: "Needs Review",
      markAccepted: "Accept",
      markReview: "Needs review",
      markRejected: "Reject"
    },
    report: {
      evidence: "Evidence",
      causes: "AI-assisted explanation",
      recommendations: "Recommendations",
      risk: "Risk",
      watch: "Watch metrics",
      confidence: "Confidence",
      high: "High",
      medium: "Medium",
      manual: "Human review required",
      ruleTitle: "Rule detection result",
      decomposition: "Metric decomposition",
      boundary: "Human approval boundary",
      boundaryText: "Budget changes, bid modifications, ad-source switching, and critical configuration changes are recommendations only and are never executed automatically.",
      fitTitle: "Why is AI assistance appropriate here?",
      fitItems: ["The issue requires multi-metric and multi-dimension decomposition, which is expensive to explain manually.", "Standard reporting surfaces change but does not readily produce cause-oriented communication.", "AI outputs stay tied to evidence and require staff confirmation before action."],
      valueTitle: "AI Assistance Value Measurement",
      simulated: "Mock data",
      actions: "Business actions"
    }
  }
};
